CREATE USER $ADMIN_NAME WITH PASSWORD '$ADMIN_PW' WITH ALL PRIVILEGES

CREATE DATABASE $DB_NAME
USE $DB_NAME

CREATE USER $DASHBOARD_NAME WITH PASSWORD '$DASHBOARD_PW'
GRANT READ ON $DB_NAME TO $DASHBOARD_NAME

CREATE USER $SCRAPER_NAME WITH PASSWORD '$SCRAPER_PW'
GRANT READ ON $DB_NAME TO $SCRAPER_NAME

